### ISSUE TITLE
No search results if Category filter is empty

### ISSUE THREAD

**Issue by munxar** [getgrav/grav-plugin-simplesearch#30] opened 2016-02-23 08:13 UTC
# Problem
When the Category filter is set to an empty string by the grav admin panel, the search result never returns a result.

## Solution
I investigated the problem and found that the check for empty filter [here](https://github.com/getgrav/grav-plugin-simplesearch/blob/develop/simplesearch.php#L113) is always false.
I think the cause is, that the $filters var is never empty it is a map containing {category: null}. I'm very new to grav and php in general, but thing it is due to the blueprint definition.

i made a [pull request](https://github.com/getgrav/grav-plugin-simplesearch/pull/31) that fixes the problem for me, but I'm not sure if it's done the "right" way.

php: 5.6.15
grav: 1.0.10
SimpleSearch: 1.6.2

**Comment by echh** [comment] 2016-02-24 11:39
I have the same problem. 
I just wanted the search to do a fulltext search on all pages. (I have no blog)
But I dont get it to work even with your proposed fix.

**Comment by flaviocopes** [comment] 2016-02-24 13:13
@munxar Pushed a fix that should address it in a slightly more general way, can you test?

@echh can you test too? if the fix does not work it's not the same problem I think

**Comment by munxar** [comment] 2016-02-24 13:35
unfortunately it's not working for me.
The Problem now is not the filter logic now, but the simple search admin page. Try this to reproduce:
1. clean grav-admin install with simpleSearch
2. remove the default entry "blog" from Category filter and save
3. route somewhere e.g. the plugin list page and go back to simpleSearch
4. "blog" is set again for Category filter
My user/config/plugins/simplesearch.yaml now looks like this:
```
enabled: true
built_in_css: true
route: /search
template: simplesearch_results
filter_combinator: and
order:
  by: date
  dir: desc
```
If I add this, like mentioned in the docs:
```
filters:
  category: []
```
everything works as expected, as long as I don't resave the plugin config from the admin page.

**Comment by echh** [comment] 2016-02-24 13:35
@flaviocopes My problem is fixed now - thank you very much

**Comment by flaviocopes** [comment] 2016-02-24 13:59
@munxar looks like a problem in the Admin settings, if nothing is entered the value is not saved. Which I think might make sense for some other fields, but not for this, as then it falls back to the default value

**Comment by munxar** [comment] 2016-02-24 14:06
my knowledge in grav is very little, but isn't the simplesearch/blueprints.yaml to configure this behaviour?

**Comment by flaviocopes** [comment] 2016-02-24 14:12
Yes, the problem is in its inner working. `filters.category` is not added to the site config, so it falls back to "blog" as it's the default value for the plugin. Digging into it

**Comment by rhukster** [comment] 2016-04-29 22:49
I think this should be sorted with current develop branch.

**Closed by rhukster** 2016-04-29 22:49 UTC

**Comment by dschwabeS11** [comment] 2018-08-02 14:53
Can we please have this fixed soon?

Adding `category: []`  to the config file still solved the issue. 
Was searching quiet a while to get this solved.

Thanks!
